### PR TITLE
Dytro

### PR DESCRIPTION
**Pull request by gitleolee**
I added more emojis.

### CODE REVIEW

**Comment by gitleolee** [comment]
Just due to my auto-format

**Comment by mikey1384** [comment]
ah okay we should sync our eslint

**Comment by mikey1384** [comment]
[image: Screen Shot 2019-10-27 at 8.39.15 PM.png]

**Comment by mikey1384** [comment]
I merged your code and updated the website

**Comment by mikey1384** [comment]
Hey,

I just signed the petition "Mayor Jacob Frey: Justice for George Floyd" and
wanted to see if you could help by adding your name.

Our goal is to reach 13,500,000 signatures and we need more support. You
can read more and sign the petition here:

http://chng.it/j5LRKkQtv6

Thanks!
Mikey

**Pull request merged**
